### ISSUE TITLE
`maxVertexOutputComponents` and `maxFragmentInputComponents` limits are too low

### ISSUE THREAD

**Issue by teoxoy** [kainino0x/gpuinfo-vulkan-query#1]
The WebGPU spec requires `maxInterStageShaderVariables` to be at least 16; that means that `maxVertexOutputComponents` and `maxFragmentInputComponents` should be at least 64.

https://github.com/kainino0x/gpuinfo-vulkan-query/blob/99f223f8007440b6f85bff10c912a0fd117d379f/query.py#L214-L215

**Comment by kainino0x** [comment]
You're right, this check predates all the work we did to figure out what we actually needed on Vulkan:
https://github.com/gpuweb/gpuweb/issues/1962#issuecomment-1136316791

Fortunately it doesn't make any difference because the Vulkan spec requires both of these values to be at least 64 anyway:
https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap45.html#limits-minmax

**Comment by teoxoy** [comment]
Just wanted to make sure it's 1:1 with the spec.

Btw, thanks for putting together this script!
I can imagine it was instrumental for the spec and also quite useful for implementors.

**Comment by kainino0x** [comment]
Glad you appreciate it! It wasn't just me, Corentin did the initial work on it :). It has been and continues to be super useful.
